<a href="https://colab.research.google.com/github/GOPIKAV77/Python/blob/main/confusion_matrix_Classification_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CONFUSION MATRIX**:

Determines how well a model is performing by with actual results.

**ROC Curve:**

It gives a visual representation of model performance.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
df = pd.read_csv("cars.csv")
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  32 non-null     object 
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64  
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64  
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64  
 9   am          32 non-null     int64  
 10  gear        32 non-null     int64  
 11  carb        32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


Here, we take Coupon as the outcome of the

In [7]:
df["vs"].unique()

array([0, 1])

In [8]:
df["vs"].value_counts()

vs
0    18
1    14
Name: count, dtype: int64

In [9]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [12]:
x = df[["mpg","cyl"]]
y = df["vs"].values.reshape(-1,1)
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.20,random_state=1)

In [13]:
len(x_train),len(x_test),len(y_train),len(y_test)

(25, 7, 25, 7)

**PREDICTION**

In [17]:
reg = LogisticRegression()
reg.fit(x_train,y_train.ravel())

LogisticRegression()

In [19]:
y_predict_test = reg.predict(x_test)
y_predict_test

array([1, 0, 0, 1, 0, 1, 0])

In [20]:
y_predict_train= reg.predict(x_train)
y_predict_train

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0])

In [25]:
y_prob_train = reg.predict_proba(x_train)[:,1]
y_prob_train.reshape(1,-1)

array([[0.05482165, 0.79923429, 0.07475185, 0.04496138, 0.42550254,
        0.89496671, 0.86603446, 0.04629755, 0.88722736, 0.85650507,
        0.05979181, 0.05676122, 0.87702289, 0.39727589, 0.37833762,
        0.05842661, 0.37833762, 0.07475185, 0.8955422 , 0.05742195,
        0.40464605, 0.88722736, 0.05024256, 0.05294464, 0.42100823]])

In [26]:
y_prob = reg.predict_proba(x_test)[:,1]
y_prob.reshape(1,-1)

array([[0.83150232, 0.37258141, 0.05676122, 0.83150232, 0.0633365 ,
        0.81359959, 0.05578351]])

**SUMMARY**

In [28]:
import statsmodels.api as sm
s = sm.add_constant(x)
l = sm.Logit(y,s)
model = l.fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.273298
         Iterations 8


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                   32
Model:                          Logit   Df Residuals:                       29
Method:                           MLE   Df Model:                            2
Date:                Wed, 26 Feb 2025   Pseudo R-squ.:                  0.6012
Time:                        13:23:15   Log-Likelihood:                -8.7455
converged:                       True   LL-Null:                       -21.930
Covariance Type:            nonrobust   LLR p-value:                 1.879e-06
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         15.9714     11.022      1.449      0.147      -5.632      37.575
mpg           -0.1633      0.240     -0.681      0.496      -0.634       0.307
cyl           -2.1482      1.081     -1.987      0.047      -4.267      -0.029
==============================================================================
"""

**CONFUSION MATRIX**

In [30]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_predict_test)
score

0.8571428571428571

85 percentage accuracy

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,  y_predict_test)

array([[3, 0],
       [1, 3]])

In [35]:
true_negative, false_positive, false_negative, true_positive = confusion_matrix(y_test, y_predict_test).ravel()
print("true negative",true_negative)
print("false positive",false_positive)
print("false negative",false_negative)
print("true positive",true_positive)

true negative 3
false positive 0
false negative 1
true positive 3


**CLASSIFICATION REPORT**

In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict_test))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         3
           1       1.00      0.75      0.86         4

    accuracy                           0.86         7
   macro avg       0.88      0.88      0.86         7
weighted avg       0.89      0.86      0.86         7

